### ISSUE TITLE
Tracking intermediate stages in data flow

### ISSUE THREAD

**Issue by ByroneCole-SageBionetworks** [include-dcc/DMC_v3_tasks#10]
- [ ]  for each dataset to be submitted in INCLUDE, a project manager completes a data plan form providing:

- dataset contributor
- target dataset submission date
- dataset type: selected among the dataset types available in the INCLUDE data model (e.g. biosample data, demographics 
- clinical data, demographics family history, bulk RNA-seq data, etc.)
- target release date
- governance access controls & PHI checklist 

- [ ]  for each dataset described in the data plan, in addition to indicating target submission date and target release date information, the DFA dashboard tracks the dataset status

- has been submitted (true/false)
- metadata have been validated (true/false)
- data have been QC-ed (true/false)
- dataset is ready for release (true/false)
- dataset is released (true/false)

- [ ]  the DFA tracks distribution of datasets across data types, contributors and release state, so that project managers and program officers can alert relevant parties for bottlenecks, etc.
