### ISSUE TITLE
test

### ISSUE THREAD

**Issue by lopierra** [include-dcc/DMC_v3_tasks#38]
```[tasklist]
### testing tasklist
- [ ] include-dcc/include-linkml#84
- [ ] include-dcc/include-linkml#80
- [ ] include-dcc/DMC_task_tracker_issues#44
```
